name: workflow
on:
  push:

jobs:
  command:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ::notice::Un message d\'information
          echo ::warning::Un message d\'avertissement
          echo ::error::Un message d\'erreur
        
  
    
