name: workflow
on:
  push:

jobs:
  command:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cloud: ovh
            endpoint: ovh-eu
          - cloud: aws
            endpoint: aws-us
        
    steps:
      - run: echo ${{ matrix.cloud }} ${{ matrix.endpoint }}
