# name: Mon premier workflow
# on: [push]
# env:
#   VAR_1: from workflow
# jobs: 
#   deploy:
#     env: 
#       VAR_2: from job
#     runs-on: ubuntu-latest
#     steps:
#       - name: hello
#         env:
#           VAR_3: from step
#         run: |
#           echo VAR_1: $VAR_1
#           echo VAR_1: ${{ env.VAR_1 }}
#           echo VAR_2: $VAR_2
#           echo VAR_3: $VAR_3
#           echo VAR_4: ${{ vars.VAR_4 }}
#           echo SECRET_1: ${{ secrets.SECRET_1 }}
#           echo GITHUB_REF: $GITHUB_REF
#           echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
#           echo GITHUB_SHA: $GITHUB_SHA
#           echo 42
#           echo ${{ 42 }}
#           echo ${{ 'main' == 'top' }}
#           echo ${{ contains(github.ref, 'main') }}
#           echo 'toto'
#       - run : echo ${{ contains(github.ref, 'main') }}
#       - run : echo ${{ 'main' == 'top' }}
#       - run : echo ${{ 42 }}
#       - run : echo TOTO
#         if: always()
          

