name: workflow
on:
  push:

jobs:
  command:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - cloud: ovh
            endpoint: ovh-eu
            os: ubuntu-latest
        
    steps:
      - run: echo ${{ matrix.cloud }} ${{ matrix.endpoint }} ${{ matrix.os }}
