name: workflow
on:
  push:

jobs:
  command:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        vers: [12, 13, 14]
        
    steps:
      - run: echo ${{ matrix.os }} ${{ matrix.vers }}
